# import sys
# import os
# sys.path.insert(1, os.getcwd())
from General import ISA

"""GENERAL"""
VSTALL = 75
VAPPROACH = 1.23*VSTALL
NLIMIT = 2.5
VMANUEVER = VSTALL*NLIMIT**0.5


"""TAKEOFF"""
TAKEOFFMACH = VAPPROACH/ISA.speedOfSound(0)

"""CRUISE"""
CRUISEALTITUDE = 11887.2
CRUISEMACH = 0.82
CRUISEVELOCITY = CRUISEMACH*ISA.speedOfSound(CRUISEALTITUDE)
CRUISEDENSITY = ISA.density(CRUISEALTITUDE)

"""LAND"""
LANDMACH = VAPPROACH/ISA.speedOfSound(0)

"""AIRFOIL"""
CLMAXAIRFOIL = 1.6
ALPHAZEROLIFT = -1.66
THICKNESSTOCHORD = 0.1
CD0 = 0.009
DCLALPHA = 0.111 #PER DEGREE

"""HIGH LIFT DEVICES"""
TAKEOFFHLDDEPLOYMENT = 0.6
KRUGERFLAPS = True
SINGLESLOTFLAPS = True




