# import sys
# import os
# sys.path.insert(1, os.getcwd())

from General import ISA

"""TAKEOFF"""
TAKEOFFMACH = 0.2

"""CRUISE"""
CRUISEALTITUDE = 11887.2
CRUISEMACH = 0.82
CRUISEVELOCITY = CRUISEMACH*ISA.speedOfSound(CRUISEALTITUDE)
CRUISEDENSITY = ISA.density(CRUISEALTITUDE)

"""LAND"""
LANDMACH = 0.2

"""AIRFOIL"""
CLMAXAIRFOIL = 1.6

"""HIGH LIFT DEVICES"""
TAKEOFFHLDDEPLOYMENT = 0.6
KRUGERFLAPS = True
SINGLESLOTFLAPS = True


